### ISSUE TITLE
Code only works in GUI if client and server are the same

### ISSUE THREAD

**Issue by alevin-fotokem** [BBj-Plugins/BBjDocViewer#8]
Line 153 in BBjDocViewer.bbj should be changed to the following 2 lines:

path$ = ::BBUtils.bbj::BBUtils.copyFileToWebServer(file$, "deliver", clean$, 0, 1)

#HTMLView!.setUrl(path$)

[BBjDocViewer.zip](https://github.com/BBj-Plugins/BBjDocViewer/files/6757272/BBjDocViewer.zip)

**Comment by StephanWald** [comment]
fixed, version 0.92 tagged
Thank you for your contribution!
